version: '3.8'

services:
  app:
    image: springio/gs-spring-boot-docker
    container_name: supermercado-app
    ports:
      - "${APP_PORT}:8080"
    environment:
      - DB_URL=jdbc:postgresql://host.docker.internal:${DB_PORT}/supermercadoDB
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - supermercado-network

  db:
    image: postgres:15-alpine
    container_name: supermercado-db
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=supermercadoDB
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - supermercado-network

volumes:
  postgres-data:


networks:
  supermercado-network:
    driver: bridge
